In [1]:
import pandas as pd
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt
df=pd.read_csv("/content/housing.data")
print(df)

     0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0     0.02731   0.00   7.070  0  0.4690  6.4210  78...                                              
1     0.02729   0.00   7.070  0  0.4690  7.1850  61...                                              
2     0.03237   0.00   2.180  0  0.4580  6.9980  45...                                              
3     0.06905   0.00   2.180  0  0.4580  7.1470  54...                                              
4     0.02985   0.00   2.180  0  0.4580  6.4300  58...                                              
..                                                 ...                                              
500   0.06263   0.00  11.930  0  0.5730  6.5930  69...                                              
501   0.04527   0.00  11.930  0  0.5730  6.1200  76...                                              
502   0.06076   0.00  11.930  0  0.5730  6.9760  91...                                     

In [ ]:
df.isnull().sum()

In [ ]:
df.describe()

In [2]:
dt=df.iloc[3]
print(dt)

 0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00     0.06905   0.00   2.180  0  0.4580  7.1470  54...
Name: 3, dtype: object


In [3]:
df.sort_index(axis=1,ascending=False)

0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0     0.02731   0.00   7.070  0  0.4690  6.4210  78...                                              
1     0.02729   0.00   7.070  0  0.4690  7.1850  61...                                              
2     0.03237   0.00   2.180  0  0.4580  6.9980  45...                                              
3     0.06905   0.00   2.180  0  0.4580  7.1470  54...                                              
4     0.02985   0.00   2.180  0  0.4580  6.4300  58...                                              
..                                                 ...                                              
500   0.06263   0.00  11.930  0  0.5730  6.5930  69...                                              
501   0.04527   0.00  11.930  0  0.5730  6.1200  76...                                              
502   0.06076   0.00  11.930  0  0.5730  6.9760  91...                                              
503   0.10959   0.00  11.930  0  0.5730  6.7940  89...                                              
504   0.04741   0.00  11.930  0  0.5730  6.0300  80...                                              

[505 rows x 1 columns]

In [4]:
print(df.iloc[2:4,3:5])

Empty DataFrame
Columns: []
Index: [2, 3]


In [5]:
print(df.iloc[:,3:5])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[505 rows x 0 columns]


In [6]:
df=np.arange(10,15)
df1=np.array([11,12,13,14,15])
print(df)
print(df1)
np.corrcoef(df,df1)

[10 11 12 13 14]
[11 12 13 14 15]


array([[1., 1.],
       [1., 1.]])

In [7]:
df=np.arange(25,30)
df1=np.array([11,15,23,25,29])
r=np.corrcoef(df,df1)
r1,p1=scipy.stats.pearsonr(df,df1)
print(r1,p1)
r2,p2=scipy.stats.spearmanr(df,df1)
print(r2,p2)
r3,p3=scipy.stats.kendalltau(df,df1)
print(r3,p3)

0.9825113063742752 0.0027690279453106
0.9999999999999999 1.4042654220543672e-24
0.9999999999999999 0.016666666666666666


In [8]:
reg=scipy.stats.linregress(df,df1)
print(reg)
print(reg.slope)
print(reg.rvalue)
print(reg.pvalue)
print(reg.stderr)
print(reg.intercept)
print(reg.intercept_stderr)

LinregressResult(slope=4.6000000000000005, intercept=-103.60000000000002, rvalue=0.9825113063742752, pvalue=0.002769027945310598, stderr=0.503322295684715, intercept_stderr=13.608330781791919)
4.6000000000000005
0.9825113063742752
0.002769027945310598
0.503322295684715
-103.60000000000002
13.608330781791919
